version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 37017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: s3cr3t
      MONGO_INITDB_DATABASE: broken
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 38081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: s3cr3t
      ME_CONFIG_MONGODB_URL: mongodb://root:s3cr3t@mongo:27017/
